### ISSUE TITLE
only works if login field names are "username" and "password"

### ISSUE THREAD

**Issue by kmulvey** [jaredhanson/connect-ensure-login#8]
My app doesn't use usernames only emails. Its not the end of the world, I just named my email field "username", but it would be nice if you could handle the POST'd values yourself can pass them into this middleware.

**Comment by jaredhanson** [comment]
I'm guessing you meant to file this against [passport-local](https://github.com/jaredhanson/passport-local), since this module doesn't look at field names.

In that case, there are `usernameField` and `passwordField` options ([code](https://github.com/jaredhanson/passport-local/blob/master/lib/passport-local/strategy.js#L49)), which you can use to override the defaults.
